sonar.projectKey=alumigest-backend
sonar.projectName=AlumiGest Backend
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/dto/**,**/domain/**,**/config/**,**/exception/**,**/br/edu/ifpb/alumigest/AlumiGestApplication.java
